name: Mosquitto Community Broker
version: "1.1.4"
slug: "mosquitto_official"
description: Inoffizielle Home-Assistant-App mit dem offiziellen Eclipse-Mosquitto-Docker-Image
url: https://github.com/Clarion30/home-assistant-mosquitto-official
arch:
  - amd64
startup: services
boot: auto
init: false
host_network: true
stage: stable
map:
  - addon_config:rw
options:
  username: mqtt
  password: ""
  debug: false
schema:
  username: str
  password: password
  debug: bool
